### ISSUE TITLE
Unable to read .fit file, mac

### ISSUE THREAD

**Issue by Halloran** [jmackie4/cycleRtools#4]
I'm trying to get the package installed on my Mac/RStudio installation, and verify it by loading a simple .fit file, but am running into what look like some java errors. Some commands and output to illustrate:
```
> file.exists("~/Fitness/2015 Garmin Files/2015-08-22-10-10-26.fit")
[1] TRUE
> library('cycleRtools')
> jhridedata <- read_ride("~/Fitness/2015 Garmin Files/2015-08-22-10-10-26.fit")
Reading .fit file...
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: /var/folders/vy/_vt6zlrx59gcg4d5l3qndb5m0000gp/T/Rtmp6TuEKb/file9a37c3d9ec5 (No such file or directory)
	at com.garmin.fit.csv.CSVTool.main(CSVTool.java:183)
Caused by: java.io.FileNotFoundException: /var/folders/vy/_vt6zlrx59gcg4d5l3qndb5m0000gp/T/Rtmp6TuEKb/file9a37c3d9ec5 (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.garmin.fit.csv.CSVTool.main(CSVTool.java:155)
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/var/folders/vy/_vt6zlrx59gcg4d5l3qndb5m0000gp/T//Rtmp6TuEKb/file9a37c3d9ec5_data.csv': No such file or directory
```
And as far as my java installation goes:
```
$ javac -version   
javac 1.8.0_91
```
Any suggestions as to what to try here would be much appreciated. Also happy to provide further detail about my system.

**Comment by jmackie4** [comment]
Could be an issue with tilde expansion, or the file itself could be
corrupted. Is the file straight from your device or pulled from Garmin
Connect?

In any case, I have a new package in the pipeline to supercede this one
that, amongst other things, handles all file parsing internally via Rcpp.
Watch this space.

**Comment by Halloran** [comment]
It looks like it was a problem with tilde expansion. Very sorry for not checking that first. 

Looking forward to working with the package!

**Comment by aas123** [comment]
Hi, I am unable to read FIT files using the package. I have tried reading files generated by my Garmin as well as files generated in Zwift. Here is a sample session:

> rm(list=ls())
> library(cycleRtools)
> 
> dat <- read_ride("2016-11-27-15-52-40.fit")

Reading .fit file...
Error in if ((diffs["count", which.max(diffs["count", ])]/length(tdat)) <  : 
  argument is of length zero
In addition: Warning message:
running command '"java"' had status 1 

> system("java -version")
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cycleRtools_1.1.1

loaded via a namespace (and not attached):
[1] tools_3.3.2 Rcpp_0.12.7 xml2_1.0.0 

Of note, I do have FitSDK installed and the java subdirectory for that package is on my path.

Thanks.
